<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integrations/owners/v1/service.proto

namespace IDBI\PHPProto\Integrations\Owners\v1\Metadata;

class Service
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        \IDBI\PHPProto\Integrations\Owners\v1\Metadata\Messages::initOnce();
        $pool->internalAddGeneratedFile(
            '
ù
$integrations/owners/v1/service.protointegrations.owners.v1google/api/field_behavior.protogoogle/protobuf/wrappers.protogoogle/protobuf/empty.protogoogle/protobuf/timestamp.protovalidate/validate.proto%integrations/owners/v1/messages.proto2à
Service}
CreateOwner*.integrations.owners.v1.CreateOwnerRequest+.integrations.owners.v1.CreateOwnerResponse"Ç”‰ì:*"
/v1/ownersBäZ1github.com/idbi/goproto/integrations/owners/v1;v1 $IDBI\\PHPProto\\Integrations\\Owners\\v1‚-IDBI\\PHPProto\\Integrations\\Owners\\v1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

