<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integrations/integrations/v1/messages.proto

namespace IDBI\PHPProto\Integrations\Integrations\v1\Metadata;

class Messages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        \IDBI\PHPProto\Integrations\Entities\v1\Metadata\Integration::initOnce();
        \IDBI\PHPProto\Integrations\Entities\v1\Metadata\Result::initOnce();
        \IDBI\PHPProto\Integrations\Entities\v1\Metadata\Owner::initOnce();
        $pool->internalAddGeneratedFile(
            '
ë
+integrations/integrations/v1/messages.protointegrations.integrations.v1google/api/field_behavior.protogoogle/protobuf/wrappers.protogoogle/protobuf/empty.protogoogle/protobuf/timestamp.protovalidate/validate.proto*integrations/entities/v1/integration.proto%integrations/entities/v1/result.proto$integrations/entities/v1/owner.proto"?
GetIntegrationsRequest%
owner_id (	B
úBrÿRownerId"ž
GetIntegrationsResponse8
result (2 .integrations.entities.v1.ResultRresultI
integrations (2%.integrations.entities.v1.IntegrationRintegrations"œ
RegisterIntegrationRequest5
owner (2.integrations.entities.v1.OwnerRownerG
integration (2%.integrations.entities.v1.IntegrationRintegration"W
RegisterIntegrationResponse8
result (2 .integrations.entities.v1.ResultRresult"´
$RegisterIntegrationParametersRequestG
integration (2%.integrations.entities.v1.IntegrationRintegrationC

parameters (2#.integrations.entities.v1.ParameterR
parameters"a
%RegisterIntegrationParametersResponse8
result (2 .integrations.entities.v1.ResultRresult"T
GetIntegrationParametersRequest1
integration_id (	B
úBrÿRintegrationId"¡
 GetIntegrationParametersResponse8
result (2 .integrations.entities.v1.ResultRresultC

parameters (2#.integrations.entities.v1.ParameterR
parameters"–
"RemoveIntegrationParametersRequest1
integration_id (	B
úBrÿRintegrationId=
parameter_ids (	BúB’d"
rÿ°RparameterIds"_
#RemoveIntegrationParametersResponse8
result (2 .integrations.entities.v1.ResultRresultBœZ7github.com/idbi/goproto/integrations/integrations/v1;v1Ê*IDBI\\PHPProto\\Integrations\\Integrations\\v1â3IDBI\\PHPProto\\Integrations\\Integrations\\v1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

