<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integrations/utils/v1/messages.proto

namespace IDBI\PHPProto\Integrations\Utils\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>integrations.utils.v1.GetVersionRequest</code>
 */
class GetVersionRequest extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \IDBI\PHPProto\Integrations\Utils\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

}

