<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integrations/tasks/v1/messages.proto

namespace IDBI\PHPProto\Integrations\Tasks\v1\Metadata;

class Messages
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        \IDBI\PHPProto\Integrations\Entities\v1\Metadata\Owner::initOnce();
        \IDBI\PHPProto\Integrations\Entities\v1\Metadata\Result::initOnce();
        \IDBI\PHPProto\Integrations\Entities\v1\Metadata\Artifact::initOnce();
        \IDBI\PHPProto\Integrations\Entities\v1\Metadata\Task::initOnce();
        \IDBI\PHPProto\Integrations\Entities\v1\Metadata\Status::initOnce();
        \IDBI\PHPProto\Integrations\Entities\v1\Metadata\Integration::initOnce();
        $pool->internalAddGeneratedFile(
            '
ä

$integrations/tasks/v1/messages.protointegrations.tasks.v1google/api/field_behavior.protogoogle/protobuf/wrappers.protogoogle/protobuf/empty.protogoogle/protobuf/timestamp.protovalidate/validate.proto$integrations/entities/v1/owner.proto%integrations/entities/v1/result.proto\'integrations/entities/v1/artifact.proto#integrations/entities/v1/task.proto%integrations/entities/v1/status.proto*integrations/entities/v1/integration.proto"‹
CreateTaskRequest2
integration_id (	BúBrÐ°RintegrationIdB

properties (2".integrations.entities.v1.PropertyR
properties"‚
CreateTaskResponse8
result (2 .integrations.entities.v1.ResultRresult2
task (2.integrations.entities.v1.TaskRtask"-
GetTaskRequest
id (	BúBrÐ°Rid"E
GetTaskResponse2
task (2.integrations.entities.v1.TaskRtask"3
GetTaskStatusRequest
id (	BúBrÐ°Rid"‰
GetTaskStatusResponse2
task (2.integrations.entities.v1.TaskRtask<
statuses (2 .integrations.entities.v1.StatusRstatuses"3
GetTaskResultRequest
id (	BúBrÐ°Rid"
GetTaskResultResponse2
task (2.integrations.entities.v1.TaskRtask@
	artifacts (2".integrations.entities.v1.ArtifactR	artifactsB‡Z0github.com/idbi/goproto/integrations/tasks/v1;v1Ê#IDBI\\PHPProto\\Integrations\\Tasks\\v1â,IDBI\\PHPProto\\Integrations\\Tasks\\v1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

