<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integrations/entities/v1/artifact.proto

namespace IDBI\PHPProto\Integrations\Entities\v1\Metadata;

class Artifact
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        \IDBI\PHPProto\Integrations\Entities\v1\Metadata\Task::initOnce();
        $pool->internalAddGeneratedFile(
            '
√
\'integrations/entities/v1/artifact.protointegrations.entities.v1google/api/field_behavior.protogoogle/protobuf/wrappers.protogoogle/protobuf/empty.protogoogle/protobuf/timestamp.protovalidate/validate.proto#integrations/entities/v1/task.proto"•
Artifact
id (	Rid
artifact (	Rartifact2
task (2.integrations.entities.v1.TaskRtask9

created_at (2.google.protobuf.TimestampR	createdAtBêZ3github.com/idbi/goproto/integrations/entities/v1;v1 &IDBI\\PHPProto\\Integrations\\Entities\\v1‚/IDBI\\PHPProto\\Integrations\\Entities\\v1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

