<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integrations/entities/v1/task.proto

namespace IDBI\PHPProto\Integrations\Entities\v1\Metadata;

class Task
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        \GPBMetadata\Google\Protobuf\Wrappers::initOnce();
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \GPBMetadata\Validate\Validate::initOnce();
        \IDBI\PHPProto\Integrations\Entities\v1\Metadata\Status::initOnce();
        \IDBI\PHPProto\Integrations\Entities\v1\Metadata\Owner::initOnce();
        $pool->internalAddGeneratedFile(
            '

#integrations/entities/v1/task.protointegrations.entities.v1google/api/field_behavior.protogoogle/protobuf/wrappers.protogoogle/protobuf/empty.protogoogle/protobuf/timestamp.protovalidate/validate.proto%integrations/entities/v1/status.proto$integrations/entities/v1/owner.proto"Ò
Task
id (	BúBrĞ°Rid
name (	B
úBrÿRname
retries (Rretries8
status (2 .integrations.entities.v1.StatusRstatus9

created_at (2.google.protobuf.TimestampR	createdAt"k
TaskProperty
id (	BúBrĞ°Rid
key (	B
úBrÿRkey 
value (	B
úBrÿRvalueBZ3github.com/idbi/goproto/integrations/entities/v1;v1Ê&IDBI\\PHPProto\\Integrations\\Entities\\v1â/IDBI\\PHPProto\\Integrations\\Entities\\v1\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

