<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integrations/integrations/v1/messages.proto

namespace IDBI\PHPProto\Integrations\Integrations\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>integrations.integrations.v1.RegisterIntegrationParametersRequest</code>
 */
class RegisterIntegrationParametersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.integrations.entities.v1.Integration integration = 1 [json_name = "integration"];</code>
     */
    protected $integration = null;
    /**
     * Generated from protobuf field <code>repeated .integrations.entities.v1.Parameter parameters = 2 [json_name = "parameters"];</code>
     */
    private $parameters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \IDBI\PHPProto\Integrations\Entities\v1\Integration $integration
     *     @type array<\IDBI\PHPProto\Integrations\Entities\v1\Parameter>|\Google\Protobuf\Internal\RepeatedField $parameters
     * }
     */
    public function __construct($data = NULL) {
        \IDBI\PHPProto\Integrations\Integrations\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.integrations.entities.v1.Integration integration = 1 [json_name = "integration"];</code>
     * @return \IDBI\PHPProto\Integrations\Entities\v1\Integration|null
     */
    public function getIntegration()
    {
        return $this->integration;
    }

    public function hasIntegration()
    {
        return isset($this->integration);
    }

    public function clearIntegration()
    {
        unset($this->integration);
    }

    /**
     * Generated from protobuf field <code>.integrations.entities.v1.Integration integration = 1 [json_name = "integration"];</code>
     * @param \IDBI\PHPProto\Integrations\Entities\v1\Integration $var
     * @return $this
     */
    public function setIntegration($var)
    {
        GPBUtil::checkMessage($var, \IDBI\PHPProto\Integrations\Entities\v1\Integration::class);
        $this->integration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .integrations.entities.v1.Parameter parameters = 2 [json_name = "parameters"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     * Generated from protobuf field <code>repeated .integrations.entities.v1.Parameter parameters = 2 [json_name = "parameters"];</code>
     * @param array<\IDBI\PHPProto\Integrations\Entities\v1\Parameter>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParameters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \IDBI\PHPProto\Integrations\Entities\v1\Parameter::class);
        $this->parameters = $arr;

        return $this;
    }

}

