<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integrations/integrations/v1/messages.proto

namespace IDBI\PHPProto\Integrations\Integrations\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>integrations.integrations.v1.RegisterIntegrationParametersRequest</code>
 */
class RegisterIntegrationParametersRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string integration_id = 1 [json_name = "integrationId", (.validate.rules) = {</code>
     */
    protected $integration_id = '';
    /**
     * Generated from protobuf field <code>repeated .integrations.entities.v1.Parameter parameters = 2 [json_name = "parameters"];</code>
     */
    private $parameters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $integration_id
     *     @type array<\IDBI\PHPProto\Integrations\Entities\v1\Parameter>|\Google\Protobuf\Internal\RepeatedField $parameters
     * }
     */
    public function __construct($data = NULL) {
        \IDBI\PHPProto\Integrations\Integrations\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string integration_id = 1 [json_name = "integrationId", (.validate.rules) = {</code>
     * @return string
     */
    public function getIntegrationId()
    {
        return $this->integration_id;
    }

    /**
     * Generated from protobuf field <code>string integration_id = 1 [json_name = "integrationId", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setIntegrationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->integration_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .integrations.entities.v1.Parameter parameters = 2 [json_name = "parameters"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     * Generated from protobuf field <code>repeated .integrations.entities.v1.Parameter parameters = 2 [json_name = "parameters"];</code>
     * @param array<\IDBI\PHPProto\Integrations\Entities\v1\Parameter>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParameters($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \IDBI\PHPProto\Integrations\Entities\v1\Parameter::class);
        $this->parameters = $arr;

        return $this;
    }

}

