<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integrations/integrations/v1/messages.proto

namespace IDBI\PHPProto\Integrations\Integrations\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>integrations.integrations.v1.RegisterIntegrationRequest</code>
 */
class RegisterIntegrationRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.integrations.entities.v1.Owner owner = 1 [json_name = "owner"];</code>
     */
    protected $owner = null;
    /**
     * Generated from protobuf field <code>.integrations.entities.v1.Integration integration = 2 [json_name = "integration"];</code>
     */
    protected $integration = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \IDBI\PHPProto\Integrations\Entities\v1\Owner $owner
     *     @type \IDBI\PHPProto\Integrations\Entities\v1\Integration $integration
     * }
     */
    public function __construct($data = NULL) {
        \IDBI\PHPProto\Integrations\Integrations\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.integrations.entities.v1.Owner owner = 1 [json_name = "owner"];</code>
     * @return \IDBI\PHPProto\Integrations\Entities\v1\Owner|null
     */
    public function getOwner()
    {
        return $this->owner;
    }

    public function hasOwner()
    {
        return isset($this->owner);
    }

    public function clearOwner()
    {
        unset($this->owner);
    }

    /**
     * Generated from protobuf field <code>.integrations.entities.v1.Owner owner = 1 [json_name = "owner"];</code>
     * @param \IDBI\PHPProto\Integrations\Entities\v1\Owner $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkMessage($var, \IDBI\PHPProto\Integrations\Entities\v1\Owner::class);
        $this->owner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.integrations.entities.v1.Integration integration = 2 [json_name = "integration"];</code>
     * @return \IDBI\PHPProto\Integrations\Entities\v1\Integration|null
     */
    public function getIntegration()
    {
        return $this->integration;
    }

    public function hasIntegration()
    {
        return isset($this->integration);
    }

    public function clearIntegration()
    {
        unset($this->integration);
    }

    /**
     * Generated from protobuf field <code>.integrations.entities.v1.Integration integration = 2 [json_name = "integration"];</code>
     * @param \IDBI\PHPProto\Integrations\Entities\v1\Integration $var
     * @return $this
     */
    public function setIntegration($var)
    {
        GPBUtil::checkMessage($var, \IDBI\PHPProto\Integrations\Entities\v1\Integration::class);
        $this->integration = $var;

        return $this;
    }

}

