<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: integrations/integrations/v1/messages.proto

namespace IDBI\PHPProto\Integrations\Integrations\v1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>integrations.integrations.v1.RemoveIntegrationPropertyRequest</code>
 */
class RemoveIntegrationPropertyRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string integration_id = 1 [json_name = "integrationId", (.validate.rules) = {</code>
     */
    protected $integration_id = '';
    /**
     * Generated from protobuf field <code>string property_ids = 2 [json_name = "propertyIds", (.validate.rules) = {</code>
     */
    protected $property_ids = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $integration_id
     *     @type string $property_ids
     * }
     */
    public function __construct($data = NULL) {
        \IDBI\PHPProto\Integrations\Integrations\v1\Metadata\Messages::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string integration_id = 1 [json_name = "integrationId", (.validate.rules) = {</code>
     * @return string
     */
    public function getIntegrationId()
    {
        return $this->integration_id;
    }

    /**
     * Generated from protobuf field <code>string integration_id = 1 [json_name = "integrationId", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setIntegrationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->integration_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string property_ids = 2 [json_name = "propertyIds", (.validate.rules) = {</code>
     * @return string
     */
    public function getPropertyIds()
    {
        return $this->property_ids;
    }

    /**
     * Generated from protobuf field <code>string property_ids = 2 [json_name = "propertyIds", (.validate.rules) = {</code>
     * @param string $var
     * @return $this
     */
    public function setPropertyIds($var)
    {
        GPBUtil::checkString($var, True);
        $this->property_ids = $var;

        return $this;
    }

}

