# based on https://github.com/mvdan/github-actions-golang
name: Buf linters

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    if: (github.actor != 'github-actions[bot]')
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        php-version: [8.1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: grpc, protobuf

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      # cache php dependencies
      - uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
            vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}

      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1

      # Run breaking change detection against the `main` branch
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: https://github.com/${{ github.repository }}.git#branch=main